name: watch
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.4.4
  connectivity_plus: ^3.0.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1
  firebase_storage: ^11.0.16
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.0
  flutter_facebook_auth: ^5.0.7
  flutter_hooks: ^0.18.6
  flutter_lints: ^2.0.1
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.2.1
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  google_fonts: ^3.0.1
  google_sign_in: ^6.0.0
  hooks_riverpod: ^2.3.1
  http: ^0.13.5
  iconsax: ^0.0.8
  image_picker: ^0.8.7
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  like_button: ^2.0.5
  logger: ^1.3.0
  marquee: ^2.2.3
  page_transition: ^2.0.9
  pinput: ^2.2.21
  shared_preferences: ^2.0.18

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
